# Generated by Django 4.0.2 on 2022-02-19 22:32

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Topics',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('short_des', models.CharField(max_length=255)),
                ('long_des', models.TextField()),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('name', models.CharField(max_length=255)),
                ('folder_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('topics', models.ManyToManyField(related_name='folders_topics', to='docstoreapp.Topics')),
            ],
        ),
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('doc', models.FileField(max_length=255, null=True, upload_to='')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folders', related_query_name='folders', to='docstoreapp.folder')),
                ('topics', models.ManyToManyField(related_name='document_topics', to='docstoreapp.Topics')),
            ],
        ),
    ]
