# Generated by Django 4.0.2 on 2022-02-19 23:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docstoreapp', '0002_alter_documents_doc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='doc',
            field=models.FileField(upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['txt'])]),
        ),
    ]
