# Generated by Django 4.0.2 on 2022-02-20 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docstoreapp', '0004_rename_name_folder_path_alter_documents_doc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='path',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='topics',
            name='short_des',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
